#!/usr/bin/env bash
set -euo pipefail

# Validates a commit subject against Conventional Commits.
#
# Usage:
#   scripts/check-commit-message.sh <file-containing-message>   # commit-msg hook
#   scripts/check-commit-message.sh --range <base>..<head>      # CI: every commit in a range
#   scripts/check-commit-message.sh --subject "<subject line>"  # CI: a PR title
#
# Accepted:
#   <type>(<scope>)!: <subject>     scope and "!" are optional
#   types: feat fix docs style refactor perf test build ci chore revert
# Merge commits, fixup!/squash! commits, and revert autogenerated subjects are skipped.

types='feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert'
pattern="^(${types})(\([a-z0-9][a-z0-9-]*\))?!?: [^ ].{0,71}$"

usage() {
  cat >&2 <<'EOF2'
Use Conventional Commits:
  <type>(<scope>)!: <subject>

Allowed types:
  feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert

Rules:
  - scope is optional, lowercase [a-z0-9-], in parentheses
  - "!" before the colon marks a breaking change
  - one space after the colon, subject non-empty, subject line <= 72 chars

Examples:
  feat(execution): add an ADBC-backed DuckDB executor
  fix: exit non-zero when a model is missing
  docs(readme): add quick start
  chore!: drop support for schema version 0
EOF2
}

# Prints a diagnostic and returns non-zero. Callers decide whether to keep
# going, so a range check can report every bad subject rather than only the
# first one.
fail() {
  printf 'Invalid commit message subject:\n\n  %s\n\n' "$1" >&2
  return 1
}

check_subject() {
  local subject="$1"
  case "$subject" in
    "Merge "*|"fixup! "*|"squash! "*|"Revert \""*) return 0 ;;
  esac
  [[ "$subject" =~ $pattern ]] || fail "$subject"
}


case "${1:-}" in
  --range)
    [[ -n "${2:-}" ]] || { echo "usage: $0 --range <base>..<head>" >&2; exit 2; }
    status=0
    while IFS= read -r line; do
      sha="${line%% *}"
      subject="${line#* }"
      if ! check_subject "$subject"; then
        echo "  in commit $sha" >&2
        echo >&2
        status=1
      fi
    done < <(git log --no-merges --format='%h %s' "$2")
    if [[ "$status" -ne 0 ]]; then
      usage
      exit 1
    fi
    ;;
  --subject)
    check_subject "${2:-}" || { usage; exit 1; }
    ;;
  "")
    echo "usage: $0 <message-file> | --range <base>..<head> | --subject <text>" >&2
    exit 2
    ;;
  *)
    # commit-msg hook: first non-comment line is the subject
    subject="$(grep -v '^#' "$1" | sed -n '1p')"
    check_subject "$subject" || { usage; exit 1; }
    ;;
esac
